SELECT
  ADDRESS."STREET"               AS ADDRESS_STREET,
  ADDRESS."ZIP"                  AS ADDRESS_ZIP,
  ADDRESS."CITY"                 AS ADDRESS_CITY,
  ADDRESS."REGION"               AS ADDRESS_REGION,
  ADDRESS."ADDITION"             AS ADDRESS_ADDITION,
  UNIT_ADDRESS."NOTE"            AS UNIT_ADDRESS_NOTE,
  UNIT."NOTE"                    AS UNIT_NOTE,
  UNIT."TYPE"                    AS UNIT_TYPE,
  UNIT."LASTNAME"                AS UNIT_LASTNAME,
  UNIT."FIRSTNAME"               AS UNIT_FIRSTNAME,
  UNIT."NAME_PART"               AS UNIT_NAME_PART,
  UNIT."POSITION"                AS UNIT_POSITION,
  UNIT."ORGANISATION"            AS UNIT_ORGANISATION,
  UNIT."DEPARTMENT"              AS UNIT_DEPARTMENT,
  UNIT."TITLE"                   AS UNIT_TITLE,
  UNIT."BIRTHDAY"                AS UNIT_BIRTHDAY,
  UNIT."NAME"                    AS UNIT_NAME,
  UNIT."VAT_ID"                  AS UNIT_VAT_ID,
  ADDRESS_TYPE."USE_POSTAL_CODE" AS ADDRESS_TYPE_USE_POSTAL_CODE,
  SALUTATION."ABBREV"            AS SALUTATION_ABBREV,
  SALUTATION."LETTER"            AS SALUTATION_LETTER,
  SALUTATION."ADDRESS"           AS SALUTATION_ADDRESS,
  NATION_ADDRESS."ISO2"          AS NATION_ADDRESS_ISO2,
  NATION_ADDRESS."ISO3"          AS NATION_ADDRESS_ISO3,
  NATION_ADDRESS."TEL"           AS NATION_ADDRESS_TEL,
  NATION_ADDRESS."NAME"          AS NATION_ADDRESS_NAME,
  NATION_ADDRESS."ENGLISH"       AS NATION_ADDRESS_ENGLISH,
  NATION_UNIT."ISO2"             AS NATION_UNIT_ISO2,
  NATION_UNIT."ISO3"             AS NATION_UNIT_ISO3,
  NATION_UNIT."TEL"              AS NATION_UNIT_TEL,
  NATION_UNIT."NAME"             AS NATION_UNIT_NAME,
  NATION_UNIT."ENGLISH"          AS NATION_UNIT_ENGLISH
FROM
    "PUBLIC"."UNIT" UNIT
    RIGHT OUTER JOIN "PUBLIC"."UNIT_ADDRESS" UNIT_ADDRESS
      ON UNIT."ID" = UNIT_ADDRESS."UNIT"
    LEFT OUTER JOIN "PUBLIC"."ADDRESS" ADDRESS
      ON UNIT_ADDRESS."ADDRESS" = ADDRESS."ID"
    LEFT OUTER JOIN "PUBLIC"."ADDRESS_TYPE" ADDRESS_TYPE
      ON UNIT_ADDRESS."ADDRESS_TYPE" = ADDRESS_TYPE."ID"
    LEFT OUTER JOIN "PUBLIC"."NATION" NATION_ADDRESS
      ON ADDRESS."NATION" = NATION_ADDRESS."ID"
    LEFT OUTER JOIN "PUBLIC"."NATION" NATION_UNIT
      ON UNIT."NATION" = NATION_UNIT."ID"
    LEFT OUTER JOIN "PUBLIC"."SALUTATION" SALUTATION
      ON UNIT."SALUTATION" = SALUTATION."ID"
WHERE UNIT_ADDRESS.ID IN ($P!{unit_address_list})